### ISSUE TITLE
[design] 메인 멘트, signup 버튼 height 조정

### ISSUE THREAD

**Issue by yookeunbyul** [prgrms-fe-devcourse/NFE1-1-3-Broken_handle_truck_fe#113]
메인에 등록하기 버튼이 사라지면서 너무 비어보이네요
뭐 추가할거 없을까요?

signup 버튼이 너무 좁아서 조금 키우면 좋을것같은데 어떠세요?
그리고 투명도를 조절하는 것보다 아예 회색?으로 해놨다가 primary색으로 바꾸는건 어떠신지!!

**Comment by ppyom** [comment]
> signup 버튼이 너무 좁아서 조금 키우면 좋을것같은데 어떠세요? 그리고 투명도를 조절하는 것보다 아예 회색?으로 해놨다가 primary색으로 바꾸는건 어떠신지!!

SignUp 버튼 크기 키우는거 좋습니다~~~~~~~~~

회색 => Primary도 좋습니다~~~~~~~~~~

아니면 disabled 일 때 아예 버튼을 숨겨버리는것도 괜찮을 것 같습니당~~~~~~

**Comment by ppyom** [comment]
> 메인에 등록하기 버튼이 사라지면서 너무 비어보이네요 뭐 추가할거 없을까요?

흠....... 카카오 로그인 버튼을 메인에도 넣는 것은 어떻게 생각하시나요....?! 약간 **카카오 계정으로 3초만에 로그인** 이런 느낌으로????!!
