### ISSUE TITLE
[setting] 기본 Response Data 타입 설정

### ISSUE THREAD

**Issue by ppyom** [prgrms-fe-devcourse/NFE1-1-3-Broken_handle_truck_fe#126]
기본 ResponseData 타입을 만드는 것에 대해 어떻게 생각하시나요...???

백엔드에서 보내주는 응답 데이터 보면 msg가 필수로 넘어오는데 {msg:string}을 타입으로 저장하는 것에 대해 어떻게 생각하시는지.......궁금합니다.............!

아래처럼 만들어서 사용할 생각입니다.......!

```ts
// response.d.ts
interface BaseApiResponse {
  msg: string;
}

// store.d.ts
interface StoreApiResponse extends BaseApiResponse {
  // ...
}
```

어떻게 생각하시나요???????????

**Comment by yookeunbyul** [comment]
네 좋습니다..!

**Comment by ppyom** [comment]
혹시 오류나는부분 어떻게 처리하고계신가요?!?!?!
제가 interceptors의 정체를 알았습니다........! 그거 쓰면 에러나도 그냥 response return하겠다고 코드 작성할 수 있는데 이것도 할까요????????

```ts
service.interceptors.response.use(null, (error) => {
  return error.response;
});
```

- 첫 번째: response가 성공일 때 실행될 함수 (현재는 없기 때문에ㅐ null)
- 두 번째: response가 실패일 때 실행될 함수

이렇게하면 기존에 실패일 때 try catch로 잡아주지 않아도 기본적으로 메시지를 받을 수 있습니다....!
